# -*- coding: utf-8 -*-
"""IDPRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DSfUPMAdqrGNBLAt2TrliWPsLKUXP52
"""

import streamlit as st
import cv2
import numpy as np
from skimage.metrics import structural_similarity as ssim

# Preprocess uploaded images
def preprocess_image(image):
    image = cv2.imdecode(np.frombuffer(image.read(), np.uint8), cv2.IMREAD_GRAYSCALE)
    image = cv2.resize(image, (400, 250))
    return image

# Compute SSIM difference
def compare_images(image1, image2):
    score, diff = ssim(image1, image2, full=True)
    diff = (diff * 255).astype("uint8")
    return score, diff

# Highlight tampered areas and extract contours
def highlight_tampered_sections(reference, test, diff):
    thresh = cv2.adaptiveThreshold(diff, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY_INV, 11, 2)
    kernel = np.ones((3,3), np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    result_image = cv2.cvtColor(test, cv2.COLOR_GRAY2BGR)
    tampered_areas = []

    for contour in contours:
        if cv2.contourArea(contour) > 50:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(result_image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            tampered_areas.append((x, y, w, h))

    return result_image, thresh, tampered_areas

# Define zone mappings for PAN fields
regions = {
    "PAN Number": (30, 10, 200, 70),
    "Candidate Name": (210, 10, 370, 70),
    "Father's/Mother's Name": (30, 80, 200, 130),
    "Date of Birth": (210, 80, 370, 130),
    "Photo": (30, 140, 160, 210),
    "QR Code": (260, 140, 390, 210),
    "Signature": (130, 210, 270, 250)
}

# Streamlit app UI
st.title("🔍 PAN Card Tampering Detection App")
st.write("Upload the original and suspected PAN card images.")

reference_file = st.file_uploader("Upload Original PAN Card", type=["png", "jpg", "jpeg"])
test_files = st.file_uploader("Upload Test PAN Cards", type=["png", "jpg", "jpeg"], accept_multiple_files=True)

if reference_file and test_files:
    ref_img = preprocess_image(reference_file)

    for test_file in test_files:
        test_img = preprocess_image(test_file)
        score, diff = compare_images(ref_img, test_img)
        result_img, thresh_img, tampered_areas = highlight_tampered_sections(ref_img, test_img, diff)

        detected_sections = set()
        for (x, y, w, h) in tampered_areas:
            cx, cy = x + w // 2, y + h // 2
            for label, (x1, y1, x2, y2) in regions.items():
                if x1 <= cx <= x2 and y1 <= cy <= y2:
                    detected_sections.add(f"❌ {label} is tampered.")

        result = "✅ Valid PAN Card" if score >= 0.7 and not detected_sections else "❌ Fake PAN Card"

        st.subheader(f"Results for: {test_file.name}")
        st.image(ref_img, caption="Original PAN Card", use_container_width=True, channels="GRAY")
        st.image(diff, caption="SSIM Difference Image", use_container_width=True, channels="GRAY")
        st.image(thresh_img, caption="Thresholded Tampering Detection Image", use_container_width=True, channels="GRAY")
        st.image(result_img, caption="Detected Tampered Sections", use_container_width=True)

        st.write(f"**SSIM Score:** {score:.4f}")
        st.write(f"**Result:** {result}")

        if detected_sections:
            st.write("**Tampered Sections Detected:**")
            for section in sorted(detected_sections):
                st.write(section)
        else:
            st.write("✅ No tampering detected.")

        st.markdown("---")